### ISSUE TITLE
network performance handling

### ISSUE THREAD

**Issue by lpuskas** [banzaicloud/telescopes#124]
As a side effect of the separation of the product info and the recommender applications, handling of network performance needs to be changed.
Initially provider specific mapping was part of the product info, however it needs to be part of the recommender.

The solution:
- the product info doesn't transform the network performance (if available) 
- the recommender (engine) has the "knowledge" of mapping between the provider specific values and the recommender

Implementation:
- the files / packages containing the mapper implementations need to be moved "closer" to the engine

**Comment by prekoa** [comment]
#126
