### ISSUE TITLE
Fix test summary in CircleCI

### ISSUE THREAD

**Issue by colin014** [banzaicloud/telescopes#96]
Change `UNKNOWN`

<img width="1358" alt="screen shot 2018-06-21 at 17 44 39" src="https://user-images.githubusercontent.com/6968817/41730030-02a67836-757b-11e8-924c-e281b814661e.png">

To see the results properly we need to run test on a per package basis. 
To achieve this, i suggest to do the following changes (the makefile to ebe adjusted accordingly)
- with the go list command we can list packages in the current project. (eg.: `go list ./...`
- for each package we can run the tests separately (eg.: `go test github.com/banzaicloud/telescopes/cmd/telescopes`)
- create the folder structure for each package in the rest results (mkdir -p test-results/github.com/banzaicloud/telescopes/cmd/telescopes
- run the junit transformer on the package tests
- upload the results

**Comment by lpuskas** [comment]
this is outdated, we're using gotestsum for a while
